#!/usr/bin/env python3
from ev3dev2.button import Button
from ev3dev2.sound import Sound

btn = Button()
sound = Sound()

while True:
    if btn.wait_for_bump('right'):
        sound.beep()
        
    if btn.wait_for_bump('left'):
        sound.beep()
        
    if btn.wait_for_bump('up'):
        sound.beep()
        
    if btn.wait_for_bump('down'):
        sound.beep()
        